export function generateRustComponents(components, sourcePaths = new Map()) {
  const modules = components
    .map((component) => generateRustComponent(component, sourcePaths.get(component.id)))
    .join("\n\n");
  return `// Generated by @voyajs/vite-plugin. Do not edit.\n${modules}\n`;
}

export function generatedComponentBinding(component) {
  const stem = rustStem(component.name);
  return {
    exportName: `voo_${stem}_mount`,
    handleName: `Voo${component.name}Handle`,
  };
}

export function generatedAdapterDefinition(component) {
  return {
    name: component.name,
    ...(component.style?.scoped ? { scopeId: generatedScopeId(component) } : {}),
    props: component.props.map((prop) => ({
      name: prop.name,
      type: javascriptType(prop.rustType),
      required: prop.required,
      ...(prop.defaultValue === undefined
        ? {}
        : { defaultValue: parseDefaultValue(prop.defaultValue, prop.rustType) }),
    })),
    events: component.events.map((event) => ({
      name: event.name,
      parameters: event.parameters.map((parameter) => parameter.name),
    })),
  };
}

export function generatedScopeId(component) {
  const source = component.id ?? component.name;
  let hash = 0x811c9dc5;
  for (let index = 0; index < source.length; index += 1) {
    hash ^= source.charCodeAt(index);
    hash = Math.imul(hash, 0x01000193);
  }
  return `voo-${(hash >>> 0).toString(16)}`;
}

function generateRustComponent(component, sourcePath) {
  const stem = rustStem(component.name);
  const moduleName = `voo_${stem}_component`;
  const { exportName, handleName } = generatedComponentBinding(component);
  const mountParameters = component.props
    .map((prop) => `, ${prop.name}: ${prop.rustType}`)
    .join("");
  const mountArguments = component.props.map((prop) => `, ${prop.name}`).join("");
  const updateMethods = component.props
    .map(
      (prop) => `
    pub fn update_${prop.name}(&self, value: ${prop.rustType}) {
        self.0.update_${prop.name}(value);
    }`,
    )
    .join("\n");

  const module = sourcePath
    ? `#[path = ${JSON.stringify(sourcePath)}]\nmod ${moduleName};`
    : `mod ${moduleName} {\n${indent(component.rust.content, 4)}\n}`;

  return `${module}

#[wasm_bindgen::prelude::wasm_bindgen]
pub struct ${handleName}(${moduleName}::Component);

#[wasm_bindgen::prelude::wasm_bindgen]
impl ${handleName} {${updateMethods}

    pub fn dispose(&mut self) {
        self.0.dispose();
    }
}

#[wasm_bindgen::prelude::wasm_bindgen]
pub fn ${exportName}(
    host: web_sys::Element${mountParameters}
) -> Result<${handleName}, wasm_bindgen::JsValue> {
    ${moduleName}::mount(host${mountArguments}).map(${handleName})
}`;
}

function rustStem(name) {
  return name
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/[^A-Za-z0-9_]/g, "_")
    .toLowerCase();
}

function javascriptType(rustType) {
  if (/^(?:[iu](?:8|16|32|64|128|size)|f(?:32|64))$/.test(rustType)) return "number";
  if (rustType === "bool") return "boolean";
  if (rustType === "String" || rustType === "str" || rustType === "&str") return "string";
  throw new Error(`Unsupported Voo prop type "${rustType}".`);
}

function parseDefaultValue(source, rustType) {
  const type = javascriptType(rustType);
  if (type === "number" && /^-?(?:\d+\.?\d*|\.\d+)$/.test(source)) return Number(source);
  if (type === "boolean" && /^(?:true|false)$/.test(source)) return source === "true";
  if (type === "string" && /^"(?:[^"\\]|\\.)*"$/.test(source)) return JSON.parse(source);
  throw new Error(`Invalid default value "${source}" for Rust type "${rustType}".`);
}

function indent(source, spaces) {
  const prefix = " ".repeat(spaces);
  return source
    .split(/\r?\n/)
    .map((line) => `${prefix}${line}`)
    .join("\n");
}
