export function generateRustComponents(components) {
  const modules = components.map(generateRustComponent).join("\n\n");
  return `// Generated by @voyajs/vite-plugin. Do not edit.\n${modules}\n`;
}

export function generatedComponentBinding(component) {
  const stem = rustStem(component.name);
  return {
    exportName: `voo_${stem}_mount`,
    handleName: `Voo${component.name}Handle`,
  };
}

function generateRustComponent(component) {
  const stem = rustStem(component.name);
  const moduleName = `voo_${stem}_component`;
  const { exportName, handleName } = generatedComponentBinding(component);
  const mountParameters = component.props
    .map((prop) => `, ${prop.name}: ${prop.rustType}`)
    .join("");
  const mountArguments = component.props.map((prop) => `, ${prop.name}`).join("");
  const updateMethods = component.props
    .map(
      (prop) => `
    pub fn update_${prop.name}(&self, value: ${prop.rustType}) {
        self.0.update_${prop.name}(value);
    }`,
    )
    .join("\n");

  return `mod ${moduleName} {
${indent(component.rust.content, 4)}
}

#[wasm_bindgen::prelude::wasm_bindgen]
pub struct ${handleName}(${moduleName}::Component);

#[wasm_bindgen::prelude::wasm_bindgen]
impl ${handleName} {${updateMethods}

    pub fn dispose(&mut self) {
        self.0.dispose();
    }
}

#[wasm_bindgen::prelude::wasm_bindgen]
pub fn ${exportName}(
    host: web_sys::Element${mountParameters}
) -> Result<${handleName}, wasm_bindgen::JsValue> {
    ${moduleName}::mount(host${mountArguments}).map(${handleName})
}`;
}

function rustStem(name) {
  return name
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/[^A-Za-z0-9_]/g, "_")
    .toLowerCase();
}

function indent(source, spaces) {
  const prefix = " ".repeat(spaces);
  return source
    .split(/\r?\n/)
    .map((line) => `${prefix}${line}`)
    .join("\n");
}
